# Generated by Django 2.2.6 on 2019-11-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=256)),
                ('short_description', models.TextField(max_length=256)),
                ('description', models.TextField(max_length=1024)),
                ('image_01', models.ImageField(blank=True, upload_to='food_images/')),
                ('image_02', models.ImageField(blank=True, upload_to='food_images/')),
                ('image_03', models.ImageField(blank=True, upload_to='food_images/')),
                ('image_04', models.ImageField(blank=True, upload_to='food_images/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comida.FoodCategory')),
            ],
        ),
    ]
