# Generated by Django 2.2.6 on 2019-11-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=512)),
                ('keywords', models.TextField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'meta',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=512)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=512)),
                ('keywords', models.TextField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'meta',
            },
        ),
    ]
