# Generated by Django 2.2.6 on 2019-11-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_title', models.CharField(max_length=256)),
                ('company_description', models.TextField(blank=True)),
                ('about_us_image_01', models.ImageField(upload_to='about_us')),
                ('about_us_image_02', models.ImageField(blank=True, upload_to='about_us')),
                ('about_us_image_03', models.ImageField(blank=True, upload_to='about_us')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('adress_line_1', models.CharField(max_length=256)),
                ('adress_line_2', models.CharField(blank=True, max_length=256)),
                ('adress_line_3', models.CharField(blank=True, max_length=256)),
                ('telephone', models.BigIntegerField()),
                ('telephone_mobile', models.BigIntegerField(blank=True)),
                ('e_mail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Company Data',
            },
        ),
        migrations.CreateModel(
            name='StaffPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('second_name', models.CharField(blank=True, max_length=128)),
                ('nickname', models.CharField(blank=True, max_length=128)),
                ('few_words_about', models.TextField(max_length=1024)),
                ('face', models.ImageField(upload_to='StaffPerson/')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.AboutUs')),
            ],
        ),
    ]
